## Лаб №2. Структуры данных

### Кортежи

In [2]:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [3]:
x1 = (1, 2, 3)

(1, 2, 3)

In [5]:
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [6]:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [7]:
length(x2)

3

In [8]:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [9]:
с = x1[2] + x1[3]

5

In [10]:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [11]:
in("tmp", x2), 0 in x2

(true, false)

### Словари

In [13]:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [14]:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [15]:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [16]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [17]:
haskey(phonebook, "Иванов И.И.")

true

In [18]:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [19]:
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [20]:
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

### Множества

In [21]:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [22]:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [23]:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [24]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [25]:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [26]:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [27]:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [28]:
issubset(S1,S4)

true

In [29]:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [30]:
pop!(S4)

2

In [31]:
S4

Set{Int64} with 3 elements:
  99
  3
  1

### Массивы

In [32]:
empty_array_1 = []

Any[]

In [33]:
empty_array_2 = (Int64)[]

Int64[]

In [34]:
empty_array_3 = (Float64)[]

Float64[]

In [35]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [36]:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [37]:
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [38]:
A

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [39]:
c = rand(1,8)

1×8 Matrix{Float64}:
 0.755904  0.343243  0.448709  0.184376  …  0.0159201  0.413771  0.276552

In [42]:
C = rand(2,3)

2×3 Matrix{Float64}:
 0.955118  0.735152  0.00377529
 0.626661  0.757855  0.212966

In [43]:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.316232  0.00373946  0.0663314
 0.183437  0.925484    0.152789
 0.274061  0.25607     0.0235033
 0.87386   0.99287     0.941415

[:, :, 2] =
 0.843512  0.78107   0.487427
 0.726634  0.303547  0.425791
 0.878806  0.418001  0.545936
 0.399024  0.322113  0.159552

In [44]:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [45]:
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [46]:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [48]:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [49]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [50]:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [51]:
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [52]:
repeat([1,2],3,3)

6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [53]:
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [54]:
a = collect(1:12)

12-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [56]:
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [57]:
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [58]:
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [59]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 15  10  15  15  13
 16  12  11  12  13
 10  11  15  12  16
 17  14  13  13  17
 10  12  13  11  19
 13  16  15  14  10
 20  18  10  15  19
 19  14  15  16  17
 12  15  11  20  18
 15  20  13  13  20

In [60]:
ar[:, 2]

10-element Vector{Int64}:
 10
 12
 11
 14
 12
 16
 18
 14
 15
 20

In [61]:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 10  13
 12  13
 11  16
 14  17
 12  19
 16  10
 18  19
 14  17
 15  18
 20  20

In [62]:
ar[:, 2:4]

10×3 Matrix{Int64}:
 10  15  15
 12  11  12
 11  15  12
 14  13  13
 12  13  11
 16  15  14
 18  10  15
 14  15  16
 15  11  20
 20  13  13

In [63]:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 16  13
 17  17
 13  10

In [64]:
ar[1, 3:end]

3-element Vector{Int64}:
 15
 15
 13

In [65]:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 10  10  10  11  10
 10  11  11  12  13
 12  12  11  12  13
 13  12  13  13  16
 15  14  13  13  17
 15  14  13  14  17
 16  15  15  15  18
 17  16  15  15  19
 19  18  15  16  19
 20  20  15  20  20

In [66]:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 10  13  15  15  15
 11  12  12  13  16
 10  11  12  15  16
 13  13  14  17  17
 10  11  12  13  19
 10  13  14  15  16
 10  15  18  19  20
 14  15  16  17  19
 11  12  15  18  20
 13  13  15  20  20

In [67]:
ar .> 14

10×5 BitMatrix:
 1  0  1  1  0
 1  0  0  0  0
 0  0  1  0  1
 1  0  0  0  1
 0  0  0  0  1
 0  1  1  0  0
 1  1  0  1  1
 1  0  1  1  1
 0  1  0  1  1
 1  1  0  0  1

In [68]:
findall(ar .> 14)

25-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(4, 1)
 CartesianIndex(7, 1)
 CartesianIndex(8, 1)
 CartesianIndex(10, 1)
 CartesianIndex(6, 2)
 CartesianIndex(7, 2)
 CartesianIndex(9, 2)
 CartesianIndex(10, 2)
 CartesianIndex(1, 3)
 CartesianIndex(3, 3)
 CartesianIndex(6, 3)
 CartesianIndex(8, 3)
 CartesianIndex(1, 4)
 CartesianIndex(7, 4)
 CartesianIndex(8, 4)
 CartesianIndex(9, 4)
 CartesianIndex(3, 5)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(7, 5)
 CartesianIndex(8, 5)
 CartesianIndex(9, 5)
 CartesianIndex(10, 5)

### Самостоятельная работа

#### 1. Даны множества: 𝐴 = {0, 3, 4, 9}, 𝐵 = {1, 3, 4, 7}, 𝐶 = {0, 1, 2, 4, 7, 8, 9}. Найти 𝑃 = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ 𝐶.

In [69]:
A = Set([0,3,4,9])

Set{Int64} with 4 elements:
  0
  4
  9
  3

In [70]:
B = Set([1,3,4,7])

Set{Int64} with 4 elements:
  4
  7
  3
  1

In [71]:
C = Set([0,1,2,4,7,8,9])

Set{Int64} with 7 elements:
  0
  4
  7
  2
  9
  8
  1

In [74]:
A_intersect_B = intersect(A,B)

Set{Int64} with 2 elements:
  4
  3

In [75]:
A_intersect_C = intersect(A,C)

Set{Int64} with 3 elements:
  0
  4
  9

In [76]:
B_intersect_C = intersect(B,C)

Set{Int64} with 3 elements:
  4
  7
  1

In [77]:
P=union(A_intersect_B, A_intersect_C, B_intersect_C)

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

#### 2. Приведите свои примеры с выполнением операций над множествами элементов разных типов.

In [78]:
x = ["apple", 40, 3.14]

3-element Vector{Any}:
   "apple"
 40
  3.14

In [79]:
y = [40, "banana", 2.17]

3-element Vector{Any}:
 40
   "banana"
  2.17

In [80]:
z = [3.14, "apple", "banana"]

3-element Vector{Any}:
 3.14
  "apple"
  "banana"

In [81]:
# разность множеств

In [82]:
x_minus_y = setdiff(x,y)

2-element Vector{Any}:
  "apple"
 3.14

In [83]:
x_minus_z = setdiff(x,z)

1-element Vector{Any}:
 40

In [84]:
z_minus_y = setdiff(z,y)

2-element Vector{Any}:
 3.14
  "apple"

In [87]:
# симметрическая разность (элементы, присутствующие только в одном из множеств)

In [86]:
x_symm_y = symdiff(x,y)

4-element Vector{Any}:
  "apple"
 3.14
  "banana"
 2.17

#### 3. Создайте разными способами:

#### 3.1) массив (1, 2, 3, … 𝑁 − 1, 𝑁 ), 𝑁 выберите больше 20;

In [88]:
N = 25

25

In [91]:
arr1 = collect(1:N)

25-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25

In [92]:
arr2 = [i for i in 1:N]

25-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25

#### 3.2) массив (𝑁, 𝑁 − 1 … , 2, 1), 𝑁 выберите больше 20;

In [94]:
arr3 = collect(N:-1:1)

25-element Vector{Int64}:
 25
 24
 23
 22
 21
 20
 19
 18
 17
 16
 15
 14
 13
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [95]:
arr4 = [i for i in N:-1:1]

25-element Vector{Int64}:
 25
 24
 23
 22
 21
 20
 19
 18
 17
 16
 15
 14
 13
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

#### 3.3) массив (1, 2, 3, … , 𝑁 − 1, 𝑁, 𝑁 − 1, … , 2, 1), 𝑁 выберите больше 20;


In [100]:
arr5 = [1:N; N:-1:1]

50-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

#### 3.4) массив с именем tmp вида (4, 6, 3);

In [101]:
tmp = [4,6,3]

3-element Vector{Int64}:
 4
 6
 3

In [103]:
tmp = collect([4,6,3])

3-element Vector{Int64}:
 4
 6
 3

#### 3.5) массив, в котором первый элемент массива tmp повторяется 10 раз;

In [105]:
rep_tmp1 = fill(tmp[1],10)

10-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4

In [107]:
rep_tmp2 = repeat([tmp[1]],10)

10-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4

#### 3.6) массив, в котором все элементы массива tmp повторяются 10 раз;

In [108]:
rep_tmp3 = repeat(tmp, 10)

30-element Vector{Int64}:
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 ⋮
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 6
 3

#### 3.7) массив, в котором первый элемент массива tmp встречается 11 раз, второй элемент — 10 раз, третий элемент — 10 раз;

In [109]:
rep_tmp4 = vcat(fill(tmp[1], 11), fill(tmp[2], 10), fill(tmp[3], 10))

31-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 ⋮
 6
 6
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [113]:
rep_tmp5 = vcat(repeat([tmp[1]], 11), repeat([tmp[2]], 10), repeat([tmp[3]], 10))

31-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 ⋮
 6
 6
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

#### 3.8) массив, в котором первый элемент массива tmp встречается 10 раз подряд, второй элемент — 20 раз подряд, третий элемент — 30 раз подряд;

In [114]:
rep_tmp6 = vcat(fill(tmp[1], 10), fill(tmp[2], 20), fill(tmp[3], 30))

60-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 6
 ⋮
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [117]:
rep_tmp7 = vcat(repeat([tmp[1]], 10), repeat([tmp[2]], 20), repeat([tmp[3]], 30))

60-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 6
 ⋮
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

#### 3.9) массив из элементов вида 2^𝑡𝑚𝑝[𝑖], 𝑖 = 1, 2, 3, где элемент 2^𝑡𝑚𝑝[3] встречается 4 раза; посчитайте в полученном векторе, сколько раз встречается цифра 6, и выведите это значение на экран;

In [119]:
tmp = [4,5,6]

3-element Vector{Int64}:
 4
 5
 6

In [122]:
array = [2^tmp[i] for i in 1:3]

3-element Vector{Int64}:
 16
 32
 64

In [123]:
array = vcat(array, fill(2^tmp[3],4))

7-element Vector{Int64}:
 16
 32
 64
 64
 64
 64
 64

In [126]:
array_str = string.(array) #преобразуем элементы в строковое значение

7-element Vector{String}:
 "16"
 "32"
 "64"
 "64"
 "64"
 "64"
 "64"

In [127]:
count_6 = sum(count(c -> c == '6', s) for s in array_str)

6

#### 3.10) вектор значений 𝑦 = 𝑒^𝑥 cos(𝑥) в точках 𝑥 = 3, 3.1, 3.2, … , 6, найдите среднее значение 𝑦;

In [132]:
x_arr = collect(3:+0.1:6)

31-element Vector{Float64}:
 3.0
 3.1
 3.2
 3.3
 3.4
 3.5
 3.6
 3.7
 3.8
 3.9
 4.0
 4.1
 4.2
 ⋮
 4.9
 5.0
 5.1
 5.2
 5.3
 5.4
 5.5
 5.6
 5.7
 5.8
 5.9
 6.0

In [135]:
y_arr = exp.(x_arr) .* cos.(x_arr) # вычисляем значение функции у для каждого х

31-element Vector{Float64}:
 -19.884530844146987
 -22.178753389342127
 -24.490696732801293
 -26.77318244299338
 -28.969237768093574
 -31.011186439374516
 -32.819774760338504
 -34.30336011037369
 -35.35719361853035
 -35.86283371230767
 -35.68773248011913
 -34.68504225166807
 -32.693695428321746
   ⋮
  25.046704998273004
  42.09920106253839
  61.99663027669454
  84.92906736250268
 111.0615860420258
 140.5250750527875
 173.40577640857734
 209.73349424783467
 249.46844055885668
 292.4867067371223
 338.5643778585117
 387.36034029093076

In [145]:
using Statistics
mean_y = mean(y_arr) # среднее значение у

[ Info: Precompiling Statistics [10745b16-79ce-11e8-11f9-7d13ad32a3b2]


53.11374594642971

#### 3.11) вектор вида (𝑥^𝑖, 𝑦^𝑗), 𝑥 = 0.1, 𝑖 = 3, 6, 9, … , 36, 𝑦 = 0.2, 𝑗 = 1, 4, 7, … , 34;


In [146]:
x=0.1

0.1

In [147]:
y=0.2

0.2

In [149]:
i = collect(3:3:36)

12-element Vector{Int64}:
  3
  6
  9
 12
 15
 18
 21
 24
 27
 30
 33
 36

In [150]:
j = collect(1:3:34)

12-element Vector{Int64}:
  1
  4
  7
 10
 13
 16
 19
 22
 25
 28
 31
 34

In [152]:
x_1 = x .^ i

12-element Vector{Float64}:
 0.0010000000000000002
 1.0000000000000004e-6
 1.0000000000000005e-9
 1.0000000000000006e-12
 1.0000000000000009e-15
 1.000000000000001e-18
 1.0000000000000012e-21
 1.0000000000000014e-24
 1.0000000000000015e-27
 1.0000000000000017e-30
 1.0000000000000018e-33
 1.000000000000002e-36

In [153]:
y_1 = y .^ j

12-element Vector{Float64}:
 0.2
 0.0016000000000000003
 1.2800000000000005e-5
 1.0240000000000006e-7
 8.192000000000005e-10
 6.5536000000000055e-12
 5.2428800000000056e-14
 4.194304000000005e-16
 3.3554432000000048e-18
 2.684354560000004e-20
 2.1474836480000035e-22
 1.717986918400003e-24

In [154]:
vector = [(xi, yj) for xi in x_1, yj in y_1]

12×12 Matrix{Tuple{Float64, Float64}}:
 (0.001, 0.2)    (0.001, 0.0016)    …  (0.001, 1.71799e-24)
 (1.0e-6, 0.2)   (1.0e-6, 0.0016)      (1.0e-6, 1.71799e-24)
 (1.0e-9, 0.2)   (1.0e-9, 0.0016)      (1.0e-9, 1.71799e-24)
 (1.0e-12, 0.2)  (1.0e-12, 0.0016)     (1.0e-12, 1.71799e-24)
 (1.0e-15, 0.2)  (1.0e-15, 0.0016)     (1.0e-15, 1.71799e-24)
 (1.0e-18, 0.2)  (1.0e-18, 0.0016)  …  (1.0e-18, 1.71799e-24)
 (1.0e-21, 0.2)  (1.0e-21, 0.0016)     (1.0e-21, 1.71799e-24)
 (1.0e-24, 0.2)  (1.0e-24, 0.0016)     (1.0e-24, 1.71799e-24)
 (1.0e-27, 0.2)  (1.0e-27, 0.0016)     (1.0e-27, 1.71799e-24)
 (1.0e-30, 0.2)  (1.0e-30, 0.0016)     (1.0e-30, 1.71799e-24)
 (1.0e-33, 0.2)  (1.0e-33, 0.0016)  …  (1.0e-33, 1.71799e-24)
 (1.0e-36, 0.2)  (1.0e-36, 0.0016)     (1.0e-36, 1.71799e-24)

#### 3.12) вектор с элементами (2^𝑖)/𝑖, 𝑖 = 1, 2, … , 𝑀, 𝑀 = 25;

In [155]:
M = 25

25

In [156]:
vec = [2^i/i for i in 1:M]

25-element Vector{Float64}:
      2.0
      2.0
      2.6666666666666665
      4.0
      6.4
     10.666666666666666
     18.285714285714285
     32.0
     56.888888888888886
    102.4
    186.1818181818182
    341.3333333333333
    630.1538461538462
   1170.2857142857142
   2184.5333333333333
   4096.0
   7710.117647058823
  14563.555555555555
  27594.105263157893
  52428.8
  99864.38095238095
 190650.18181818182
 364722.0869565217
 699050.6666666666
      1.34217728e6

#### 3.13) вектор вида (”fn1”, ”fn2”, …, ”fnN”), 𝑁 = 30;

In [157]:
N = 30

30

In [160]:
vec = ["fn$i" for i in 1:N]

30-element Vector{String}:
 "fn1"
 "fn2"
 "fn3"
 "fn4"
 "fn5"
 "fn6"
 "fn7"
 "fn8"
 "fn9"
 "fn10"
 "fn11"
 "fn12"
 "fn13"
 ⋮
 "fn19"
 "fn20"
 "fn21"
 "fn22"
 "fn23"
 "fn24"
 "fn25"
 "fn26"
 "fn27"
 "fn28"
 "fn29"
 "fn30"

#### 3.14) векторы 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛) и 𝑦 = (𝑦1, 𝑦2, … , 𝑦𝑛) целочисленного типа длины 𝑛 = 250 как случайные выборки из совокупности 0, 1, … , 999; на его основе:
#### – сформируйте вектор (𝑦2 − 𝑥1, … , 𝑦𝑛 − 𝑥𝑛−1);

In [161]:
n = 250

250

In [162]:
x = rand(0:999, n)

250-element Vector{Int64}:
 864
 686
 571
 930
   4
 355
 133
 435
 747
 266
 591
 725
 249
   ⋮
 347
 196
 799
  67
 358
 387
 888
 681
 703
 220
 445
 465

In [163]:
y = rand(0:999, n)

250-element Vector{Int64}:
 305
 279
 698
 161
 938
 224
 501
 925
  12
 950
 630
 673
 117
   ⋮
 421
 555
 248
 621
 363
 884
 292
 162
 884
 574
 968
 979

In [164]:
z = [y[i] - x[i-1] for i in 2:n]

249-element Vector{Int64}:
 -585
   12
 -410
    8
  220
  146
  792
 -423
  203
  364
   82
 -608
  457
    ⋮
  380
  208
   52
 -178
  296
  526
  -95
 -726
  203
 -129
  748
  534

#### – сформируйте вектор (𝑥_1 + 2𝑥_2 − 𝑥_3, 𝑥_2 + 2𝑥_3 − 𝑥_4, … , 𝑥 _ (𝑛−2) + 2𝑥 _ (𝑛−1) − 𝑥_𝑛);

In [165]:
w = [x[i] + 2 * x[i+1] - x[i+2] for i in 1:(n-2)]

248-element Vector{Int64}:
 1665
  898
 2427
  583
  581
  186
  256
 1663
  688
  723
 1792
  882
  405
    ⋮
 -156
  539
  -60
 1727
  575
  396
  244
 1482
 1547
 1867
  698
  645

#### – сформируйте вектор (sin(𝑦1)/cos(𝑥2),sin(𝑦2)/cos(𝑥3), … ,sin(𝑦𝑛−1)/cos(𝑥𝑛));

In [167]:
v = [sin(y[i]) / cos(x[i+1]) for i in 1:(n-1)]

249-element Vector{Float64}:
 -0.6186956831914913
  0.7884094781497084
  0.5387357223244303
  1.0746035961451448
 -0.9726090507625443
 -1.6400617450365744
 -9.02950553457859
  1.2806243337725127
  1.0516852087426813
  1.0183271971696686
 -1.3082091917468857
 -0.9375345044954884
  5.04286517006331
  ⋮
 -6.782300493921139
  0.07761720056626209
  1.7118986188849938
 -0.3568228956127364
 -0.8687287571693045
  1.185981622331974
  1.9530748361272352
 -0.22366866955417009
 -1.2977795773248022
 -0.940163700204414
  1.7638814531785603
  0.3800640621185212

#### – вычислите 𝑛−1∑𝑖=1 𝑒^(−𝑥_(𝑖+1))/𝑥_𝑖 + 10;

In [168]:
S = sum(exp(-x[i+1]) / (x[i] + 10) for i in 1:(n-1))

7.859818698636493e-5

#### – выберите элементы вектора 𝑦, значения которых больше 600, и выведите на экран; определите индексы этих элементов;


In [170]:
y1 = y[y .> 600]

106-element Vector{Int64}:
 698
 938
 925
 950
 630
 673
 706
 636
 822
 863
 946
 978
 991
   ⋮
 727
 743
 828
 714
 787
 740
 618
 621
 884
 884
 968
 979

In [173]:
ind_y = findall(y .> 600)

106-element Vector{Int64}:
   3
   5
   8
  10
  11
  12
  14
  15
  22
  24
  30
  31
  32
   ⋮
 224
 225
 227
 228
 233
 234
 235
 242
 244
 247
 249
 250

#### – определите значения вектора 𝑥, соответствующие значениям вектора 𝑦, значения которых больше 600 (под соответствием понимается расположение на аналогичных индексных позициях);

In [174]:
x1 = x[ind_y]

106-element Vector{Int64}:
 571
   4
 435
 266
 591
 725
 341
 526
 264
 548
 896
 320
 121
   ⋮
   8
 882
 928
 275
  15
 345
 620
  67
 387
 703
 445
 465

#### – сформируйте вектор (|𝑥1 − !𝑥|^1/2, |𝑥2 − !𝑥|^1/2, … , |𝑥𝑛 − !𝑥|^1/2 ), где 𝑥 обозначает среднее значение вектора 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛);

In [176]:
using Statistics
mean_x = mean(x)

485.664

In [177]:
v = sqrt.(abs.(x .- mean_x))

250-element Vector{Float64}:
 19.45086116345495
 14.154010032496092
  9.23774864347369
 21.079278925048648
 21.946844875744667
 11.43083549002434
 18.779350361500793
  7.1178648483937925
 16.165890015709003
 14.821066088510637
 10.263332792032031
 15.470488033672371
 15.383887675096954
  ⋮
 11.775567926856011
 17.019518207046872
 17.701299387333123
 20.46128050733873
 11.298849498953421
  9.932975385049536
 20.058314984065834
 13.976265595644639
 14.742320034512886
 16.29920243447513
  6.376833069792559
  4.545767261970194

#### – определите, сколько элементов вектора 𝑦 отстоят от максимального значения не более, чем на 200;

In [178]:
max_y = maximum(y)

998

In [179]:
Sum = sum(abs.(y .- max_y) .<= 200)

57

#### – определите, сколько чётных и нечётных элементов вектора 𝑥;

In [180]:
even_x = sum(x .%2 .== 0)

118

In [181]:
odd_x = sum(x .%2 .== 1)

132

#### – определите, сколько элементов вектора 𝑥 кратны 7;

In [182]:
x_7 = sum(x .%7 .== 0)

34

#### – отсортируйте элементы вектора 𝑥 в порядке возрастания элементов вектора 𝑦;

In [183]:
sort_ind = sortperm(y)

250-element Vector{Int64}:
 118
  63
 182
 230
  21
  71
   9
 114
 195
  69
 209
 121
 220
   ⋮
 123
  45
  31
 250
 165
 153
 100
  32
  34
  33
  76
 181

In [184]:
sort_x = x[sort_ind]

250-element Vector{Int64}:
 504
 387
  32
 113
 749
 161
 747
 739
 921
 901
 973
 785
 442
   ⋮
 369
 766
 320
 465
 314
 105
 135
 121
  15
 299
 906
 538

#### – выведите элементы вектора 𝑥, которые входят в десятку наибольших (top-10)

In [185]:
top_10 = sort(x, rev=true)[1:10]

10-element Vector{Int64}:
 994
 992
 986
 975
 973
 960
 950
 950
 940
 938

#### – сформируйте вектор, содержащий только уникальные (неповторяющиеся) элементы вектора 𝑥.

In [186]:
unique_x = unique(x)

220-element Vector{Int64}:
 864
 686
 571
 930
   4
 355
 133
 435
 747
 266
 591
 725
 249
   ⋮
 113
 782
 345
 478
 109
  41
 196
 799
 358
 888
 220
 445

#### 4. Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1 до 100.

In [187]:
squares = [i^2 for i in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

#### 5. Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте массив myprimes, в котором будут храниться первые 168 простых чисел. Определите 89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента включительно, содержащий наименьшие простые числа.


In [198]:
using Primes
myprimes = primes(1000)

168-element Vector{Int64}:
   2
   3
   5
   7
  11
  13
  17
  19
  23
  29
  31
  37
  41
   ⋮
 919
 929
 937
 941
 947
 953
 967
 971
 977
 983
 991
 997

In [199]:
prime_89 = myprimes[89]

461

In [200]:
primes_slice = myprimes[89:99]

11-element Vector{Int64}:
 461
 463
 467
 479
 487
 491
 499
 503
 509
 521
 523

#### 6. Вычислите следующие выражения:
#### 6.1)100∑𝑖=10(𝑖^3 + 4𝑖^2);

In [204]:
Sum = sum(i^3 + 4*i^2 for i in 10:100)

26852735

#### 6.2)𝑀∑𝑖=1 (2^𝑖/𝑖 +3^𝑖/𝑖^2 ), 𝑀 = 25;

In [211]:
M=25
Sum1 = sum((2^i / i + 3^i / i^2) for i in 1:M)

2.1291704368143802e9

#### 6.3) 1 +2/3+ (2/3 * 4/5) + (2/3 * 4/5 * 6/7) + ⋯ + (2/3 * 4/5 … 38/39).

In [213]:
result = 1.0
product = 1.0

1.0

In [214]:
for i in 1:19
    product *= (2*i) / (2*i + 1)
    result += product
end

In [215]:
println(result)

6.976346137897618
