## Шаповалова Диана Дмитриевна. 1032211220

## Лаб №3. Управляющие структуры

### 3.2.1 Циклы while и for

In [1]:
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
n += 1
println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
friend = myfriends[i]
println("Hi $friend, it's great to see you!")
i += 1
end


Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for n in 1:2:10
println(n)
end
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
println("Hi $friend, it's great to see you!")
end

1
3
5
7
9
Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [5]:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end

### 3.2.2. Условные выражения

In [8]:
N = 3
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
if (N % 3 == 0) && (N % 5 == 0)
println("FizzBuzz")
elseif N % 3 == 0
println("Fizz")
elseif N % 5 == 0
println("Buzz")
else
println(N)
end

Fizz


### 3.2.3. Функции

In [9]:
# Задаём матрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [13]:
# Вызываем функцию f возведения в квадрат
f(x) = x^2
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [14]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [35]:
using Colors
palette = distinguishable_colors(100)
rand(palette, 3, 3)

### 3.4. Задания для самостоятельного выполнения

#### 1. Используя циклы while и for: 
#### – выведите на экран целые числа от 1 до 100 и напечатайте их квадраты;

In [37]:
for i in 1:100
    println("Число: $i, Квадрат: $(i^2)")
end

Число: 1, Квадрат: 1
Число: 2, Квадрат: 4
Число: 3, Квадрат: 9
Число: 4, Квадрат: 16
Число: 5, Квадрат: 25
Число: 6, Квадрат: 36
Число: 7, Квадрат: 49
Число: 8, Квадрат: 64
Число: 9, Квадрат: 81
Число: 10, Квадрат: 100
Число: 11, Квадрат: 121
Число: 12, Квадрат: 144
Число: 13, Квадрат: 169
Число: 14, Квадрат: 196
Число: 15, Квадрат: 225
Число: 16, Квадрат: 256
Число: 17, Квадрат: 289
Число: 18, Квадрат: 324
Число: 19, Квадрат: 361
Число: 20, Квадрат: 400
Число: 21, Квадрат: 441
Число: 22, Квадрат: 484
Число: 23, Квадрат: 529
Число: 24, Квадрат: 576
Число: 25, Квадрат: 625
Число: 26, Квадрат: 676
Число: 27, Квадрат: 729
Число: 28, Квадрат: 784
Число: 29, Квадрат: 841
Число: 30, Квадрат: 900
Число: 31, Квадрат: 961
Число: 32, Квадрат: 1024
Число: 33, Квадрат: 1089
Число: 34, Квадрат: 1156
Число: 35, Квадрат: 1225
Число: 36, Квадрат: 1296
Число: 37, Квадрат: 1369
Число: 38, Квадрат: 1444
Число: 39, Квадрат: 1521
Число: 40, Квадрат: 1600
Число: 41, Квадрат: 1681
Число: 42, Квадрат: 1764
Чи

#### – создайте словарь squares, который будет содержать целые числа в качестве ключей и квадраты в качестве их пар-значений;

In [38]:
squares = Dict()
for i in 1:100
    squares[i] = i^2
end
println(squares)

Dict{Any, Any}(5 => 25, 56 => 3136, 35 => 1225, 55 => 3025, 60 => 3600, 30 => 900, 32 => 1024, 6 => 36, 67 => 4489, 45 => 2025, 73 => 5329, 64 => 4096, 90 => 8100, 4 => 16, 13 => 169, 54 => 2916, 63 => 3969, 86 => 7396, 91 => 8281, 62 => 3844, 58 => 3364, 52 => 2704, 12 => 144, 28 => 784, 75 => 5625, 23 => 529, 92 => 8464, 41 => 1681, 43 => 1849, 11 => 121, 36 => 1296, 68 => 4624, 69 => 4761, 98 => 9604, 82 => 6724, 85 => 7225, 39 => 1521, 84 => 7056, 77 => 5929, 7 => 49, 25 => 625, 95 => 9025, 71 => 5041, 66 => 4356, 76 => 5776, 34 => 1156, 50 => 2500, 59 => 3481, 93 => 8649, 2 => 4, 10 => 100, 18 => 324, 26 => 676, 27 => 729, 42 => 1764, 87 => 7569, 100 => 10000, 79 => 6241, 16 => 256, 20 => 400, 81 => 6561, 19 => 361, 49 => 2401, 44 => 1936, 9 => 81, 31 => 961, 74 => 5476, 61 => 3721, 29 => 841, 94 => 8836, 46 => 2116, 57 => 3249, 70 => 4900, 21 => 441, 38 => 1444, 88 => 7744, 78 => 6084, 72 => 5184, 24 => 576, 8 => 64, 17 => 289, 37 => 1369, 1 => 1, 53 => 2809, 22 => 484, 47 => 220

#### – создайте массив squares_arr, содержащий квадраты всех чисел от 1 до 100.

In [40]:
squares_arr = []
i = 1
while i <= 100
    push!(squares_arr, i^2)
    i += 1
end
println(squares_arr)

Any[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


#### 2. Напишите условный оператор, который печатает число, если число чётное, и строку «нечётное», если число нечётное. Перепишите код, используя тернарный оператор.

In [42]:
function even_odd(n)
    if n % 2 == 0
        println(n)
    else
        println("Нечетное")
    end
end
even_odd(3)
even_odd(4)

Нечетное
4


In [44]:
function even_odd_ternary(n)
    println(n % 2 == 0 ? n : "нечётное")
end
even_odd(3)
even_odd(4)

Нечетное
4


#### 3. Напишите функцию add_one, которая добавляет 1 к своему входу

In [49]:
function add_one(x)
    return x+1
end
println(add_one(-1))
println(add_one(3))

0
4


#### 4. Используйте map() или broadcast() для задания матрицы 𝐴, каждый элемент которой увеличивается на единицу по сравнению с предыдущим.

In [57]:
add_one(x) = x+1
A = reshape(1:9, 3, 3)
a = map(add_one, A)
println("Матрица A:")
println(A)
println("Матрица a:")
println(a)

Матрица A:
[1 4 7; 2 5 8; 3 6 9]
Матрица a:
[2 5 8; 3 6 9; 4 7 10]


#### 5. Задайте матрицу 𝐴 следующего вида: [1 1 3; 5 2 6; -2 -1 -3]
#### – Найдите 𝐴^3

In [67]:
A = [1 1 3; 5 2 6; -2 -1 -3]
f(x) = x^3
println("Матрица A:")
println(A)
println("Матрица A^3:")
println(f(A))

Матрица A:
[1 1 3; 5 2 6; -2 -1 -3]
Матрица A^3:
[0 0 0; 0 0 0; 0 0 0]


#### – Замените третий столбец матрицы 𝐴 на сумму второго и третьего столбцов

In [70]:
A[:, 3]= A[:,2] + A[:,3]
println(A)

[1 1 6; 5 2 12; -2 -1 -6]


#### 6. Создайте матрицу 𝐵 с элементами 𝐵_𝑖1 = 10, 𝐵_𝑖2 = −10, 𝐵_𝑖3 = 10, 𝑖 = 1, 2, … , 15.
#### Вычислите матрицу 𝐶 = (𝐵^𝑇)*𝐵

In [73]:
B = repeat([10 -10 10], 15, 1)

15×3 Matrix{Int64}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [74]:
C = B' * B

3×3 Matrix{Int64}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

#### 7. Создайте матрицу 𝑍 размерности 6 × 6, все элементы которой равны нулю, и матрицу 𝐸, все элементы которой равны 1. Используя цикл while или for и закономерности расположения элементов, создайте следующие матрицы размерности 6 × 6:

In [1]:
# Функция для красивого вывода матриц
function print_matrix(mat)
    for row in eachrow(mat)
        println(row)
    end
    println()
end

Z = zeros(Int, 6, 6)  # Матрица Z размерности 6x6, все элементы равны нулю

# Функция для создания матрицы Z_1
function create_Z1()
    Z1 = copy(Z)  # Копируем матрицу Z
    for i in 1:6
        for j in 1:6
            if abs(i - j) == 1 || i == j
                Z1[i, j] = 1
            end
        end
    end
    return Z1
end

# Матрица Z1
Z1 = copy(Z)
for i in 1:6
    for j in 1:6
        if abs(i - j) == 1  
            Z1[i, j] = 1
        end
    end
end

# Матрица Z4
Z4 = copy(Z)  
for i in 1:6
    for j in 1:6
        if (i + j) % 2 == 0  
            Z4[i, j] = 1
        end
    end
end


println("Матрица Z:")
print_matrix(Z)

println("Матрица Z_1:")
print_matrix(Z1)

println("Матрица Z_4:")
print_matrix(Z4)

Матрица Z:
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]

Матрица Z_1:
[0, 1, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0]
[0, 1, 0, 1, 0, 0]
[0, 0, 1, 0, 1, 0]
[0, 0, 0, 1, 0, 1]
[0, 0, 0, 0, 1, 0]

Матрица Z_4:
[1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1]



#### №8. В языке R есть функция outer(). Фактически, это матричное умножение с возможностью изменить применяемую операцию (например, заменить произведение на сложение или возведение в степень):
#### 8.1) Напишите свою функцию, аналогичную функции outer() языка R. Функция должна иметь следующий интерфейс: outer(x,y,operation):

In [2]:
function outer(x, y, operation)
    return [operation(xi, yj) for xi in x, yj in y]
end

outer (generic function with 1 method)

#### 8.2) Используя написанную вами функцию outer(), создайте матрицы следующей структуры:

In [3]:
# Матрица A1: сложение элементов
A1 = outer(0:4, 0:4, +)

# Матрица A2: возведение в степень (если 0^0, принимаем как 0)
function safe_pow(x, y)
    x == 0 && y == 0 ? 0 : x^y
end

# Матрица A2: с пропуском первого элемента в каждой строке
A2 = [j == 1 ? i : safe_pow(i, j) for i in 0:4, j in 1:5]

# Матрица A3: циклический сдвиг по модулю 5
A3 = outer(0:4, 0:4, (x, y) -> mod(x + y, 5))

# Матрица A4: циклический сдвиг по модулю 10
A4 = outer(0:9, 0:9, (x, y) -> mod(x + y, 10))

# Матрица A5: разница по модулю 9
A5 = outer(0:8, 0:8, (x, y) -> mod(x - y, 9))

# Функция для красивого вывода матриц
function print_matrix(name, mat)
    println("\nМатрица $name:")
    for row in eachrow(mat)
        println(row)
    end
end

# Печатаем все матрицы
print_matrix("A1", A1)
print_matrix("A2", A2)
print_matrix("A3", A3)
print_matrix("A4", A4)
print_matrix("A5", A5)


Матрица A1:
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]

Матрица A2:
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
[2, 4, 8, 16, 32]
[3, 9, 27, 81, 243]
[4, 16, 64, 256, 1024]

Матрица A3:
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 0]
[2, 3, 4, 0, 1]
[3, 4, 0, 1, 2]
[4, 0, 1, 2, 3]

Матрица A4:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[2, 3, 4, 5, 6, 7, 8, 9, 0, 1]
[3, 4, 5, 6, 7, 8, 9, 0, 1, 2]
[4, 5, 6, 7, 8, 9, 0, 1, 2, 3]
[5, 6, 7, 8, 9, 0, 1, 2, 3, 4]
[6, 7, 8, 9, 0, 1, 2, 3, 4, 5]
[7, 8, 9, 0, 1, 2, 3, 4, 5, 6]
[8, 9, 0, 1, 2, 3, 4, 5, 6, 7]
[9, 0, 1, 2, 3, 4, 5, 6, 7, 8]

Матрица A5:
[0, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 0, 8, 7, 6, 5, 4, 3, 2]
[2, 1, 0, 8, 7, 6, 5, 4, 3]
[3, 2, 1, 0, 8, 7, 6, 5, 4]
[4, 3, 2, 1, 0, 8, 7, 6, 5]
[5, 4, 3, 2, 1, 0, 8, 7, 6]
[6, 5, 4, 3, 2, 1, 0, 8, 7]
[7, 6, 5, 4, 3, 2, 1, 0, 8]
[8, 7, 6, 5, 4, 3, 2, 1, 0]


#### 9.Решите следующую систему линейных уравнений с 5 неизвестными:
#### 𝑥1 + 2𝑥2 + 3𝑥3 + 4𝑥4 + 5𝑥5 = 7,
#### 2𝑥1 + 𝑥2 + 2𝑥3 + 3𝑥4 + 4𝑥5 = −1,
#### 3𝑥1 + 2𝑥2 + 𝑥3 + 2𝑥4 + 3𝑥5 = −3,
#### 4𝑥1 + 3𝑥2 + 2𝑥3 + 𝑥4 + 2𝑥5 = 5,
#### 5𝑥1 + 4𝑥2 + 3𝑥3 + 2𝑥4 + 𝑥5 = 17

In [83]:
A = [1 2 3 4 5; 2 1 2 3 4; 3 2 1 2 3; 4 3 2 1 2; 5 4 3 2 1]
y = [7; -1; -3; 5; 17]
x = A \ y
println(x)

[-2.0000000000000036, 3.0000000000000058, 4.999999999999998, 1.9999999999999991, -3.999999999999999]


#### 10. Создайте матрицу 𝑀 размерности 6 × 10, элементами которой являются целые числа, выбранные случайным образом с повторениями из совокупности 1, 2, … , 10.
#### – Найдите число элементов в каждой строке матрицы 𝑀, которые больше числа 𝑁 (например, 𝑁 = 4).

In [84]:
M = rand(1:10, 6, 10)

6×10 Matrix{Int64}:
  4  1  3  3   5  10  9  8  4  10
  2  5  1  4   6   4  3  5  1   7
  2  9  6  1  10   8  3  9  5   4
  8  5  5  7   4   6  3  9  7   6
  5  1  2  6   4   6  2  5  1   6
 10  8  9  3   3   4  7  7  1   5

In [88]:
N = 4
count = [sum(M[i, :] .> N) for i in 1:6]
println(count)

[5, 4, 6, 8, 5, 6]


#### – Определите, в каких строках матрицы 𝑀 число 𝑀(например,𝑀 = 7) встречается ровно 2 раза?

In [89]:
two_M = [i for i in 1:6 if sum(M[i,:] .== 7) == 2]
println(two_M)

[4, 6]


#### – Определите все пары столбцов матрицы 𝑀, сумма элементов которых больше 𝐾 (например, 𝐾 = 75)

In [93]:
column_pairs = []
K = 75
for i in 1:10
    for j in i+1:10
        sum_columns = sum(M[:, i]) + sum(M[:, j])  # сумма элементов пары столбцов
        if sum_columns > K
            push!(column_pairs, (i, j))
        end
    end
end
println(column_pairs)

Any[(6, 8), (6, 10), (8, 10)]


#### 11. Вычислите: ∑_{𝑖=1}^20 ∑_{j=1}^5 𝑖^4/(3 + 𝑗)

In [95]:
sum_res= 0
for i in 1:20
    inner_sum = 0
    for j in 1:5
        inner_sum += i^4 / (3+j)
    end
    sum_res += inner_sum
end
println(sum_res)

639215.2833333334


####  ∑_{𝑖=1}^20 ∑_{j=1}^5 𝑖^4/(3 + i𝑗)

In [96]:
sum_res= 0
for i in 1:20
    inner_sum = 0
    for j in 1:5
        inner_sum += i^4 / (3+i*j)
    end
    sum_res += inner_sum
end
println(sum_res)

89912.02146097136
